### ISSUE TITLE
A simple may-be error reporting

### ISSUE THREAD

**Issue by jae-ohk** [open-simulation-platform/workshop-tutorial#1]
Line 6 in "osp-workshop-tutorial-step1/VesselModel_OspModelDescription.xml"

 Present :
 https://github.com/open-simulation-platform/workshop-tutorial/blob/6ad953345fa90a71a008a017097e02e83f7fb4c2/osp-workshop-tutorial-step1/VesselModel_OspModelDescription.xml#L6

 To-be :
 <BaseUnit kg="0" m="1" ...

 Am I right?

 As I'm not familiar with GitHub, I'm not sure weather this "Issues" page is the right place to report this.
 Thanks for your kind considerations.

**Comment by kyllingstad** [comment]
I think this error is actually a deliberate part of the tutorial. :) Note that the error is not present in the “solution”, i.e., in step 2. It's a long time since we created the tutorial, though, so I may be wrong in this.

**Comment by jae-ohk** [comment]
That's all right.
 I'd just like to be sure.
 Thanks.
