### ISSUE TITLE
What to do for a different dynamic positioning?

### ISSUE THREAD

**Issue by jae-ohk** [open-simulation-platform/workshop-tutorial#2]
During Step 3, I'd like to modify the dynamic positioning plan.
 That is, instead of target posiion (40, 0) at time 500, the same target position at time "400" for example.

 I found the dynamic positioning plan was defined in the "modelDescription.xml" zipped into "BoxReference.fmu", and modified accordingly.
 But I obtained the same results - there was nothing changed!

 What's wrong with me?

**Comment by kyllingstad** [comment]
The `modelDescription.xml` file in an FMU is a *description* of the FMU, not a *definition* of it. Changing it only means that the description no longer matches the actual FMU behaviour. Parameters and initial values must be changed from the outside, in your co-simulation setup. (For OSP software, this would be done in an  `OspSystemStructure.xml` or SSP file.)

**Comment by jae-ohk** [comment]
Thanks for your reply, before everything else.
 Unfortunately, however, I cannot find out any line which allows me to re-define the target position in "OspSystemStructure.xml" you addressed.
 I was looking, in fact, for something like "<Real start="40.0"/>", which I found out in "modelDescription.xml" zipped into "BoxReference.fum" I addressed.
 Thanks again for your kind consideration.

**Comment by kyllingstad** [comment]
You need to add `<InitialValues><InitialValue>` elements under the relevant `<Simulator>` element. See the [Simulation configuration](https://open-simulation-platform.github.io/libcosim/configuration) docs for more info. You can also look at the [libcosim tests](https://github.com/open-simulation-platform/libcosim/blob/master/tests/data/msmi/OspSystemStructure.xml) for an example.

**Comment by jae-ohk** [comment]
Thanks kyllingstad.
I'm studying OSP further according to your guide.
But it'll take some time, and thus I'd better close this issue at this moment.
Thanks a lot.
